### ISSUE TITLE
we-cropper 2.0 roadmap

### ISSUE THREAD

**Issue by dlhandsome** [dlhandsome/Blog#2]

**Comment by dlhandsome** [comment]
# version 1.x TODO

### core

- [ ] `$instance.setOption` : 用于动态改变构造器参数的方法

### 生态

- [ ] 实现基于原生组件的 `we-cropper` 版本

- [ ] 实现 `wepy` 组件，并发布 npm package，尝试修复 `wepy` npm resolve 路径问题
